version: '3'
services: 
    web:
        build: .
        ports:
            - 8080:8080
    db:
        image: mysql:latest
        ports:
            - 3309:3306
        environment: 
            MYSQL_DATABASE: lms
            MYSQL_USER: lms
            MYSQL_PASSWORD: lms
            MYSQL_ROOT_PASSWORD: root